name: cloudAnimal
favicon: null
layout_spectrum: 0.6522444591391832
typography_spectrum: 0.9361928608268499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6444700222928077
  lightness: 0.7804210914764553
  saturation: 0.9834238865878433
  rhythmicContrast: 0.16364199062809348
purpose: []
